/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Opt(IDL.Text),
});
export const PaginationResult_1 = IDL.Record({
  'total_pages' : IDL.Nat,
  'total_items' : IDL.Nat,
  'has_next_page' : IDL.Bool,
  'current_page' : IDL.Nat,
  'items' : IDL.Vec(Category),
  'has_prev_page' : IDL.Bool,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'image' : IDL.Opt(IDL.Text),
  'price' : IDL.Nat,
});
export const PaginationResult = IDL.Record({
  'total_pages' : IDL.Nat,
  'total_items' : IDL.Nat,
  'has_next_page' : IDL.Bool,
  'current_page' : IDL.Nat,
  'items' : IDL.Vec(Product),
  'has_prev_page' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'addCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'editProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'getAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCategories' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginationResult_1],
      ['query'],
    ),
  'getProducts' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginationResult],
      ['query'],
    ),
  'getProductsByCategory' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginationResult],
      ['query'],
    ),
  'getUser' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'initializeAuth' : IDL.Func([], [], []),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAdmin' : IDL.Func([IDL.Principal], [], []),
  'setUser' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Opt(IDL.Text),
  });
  const PaginationResult_1 = IDL.Record({
    'total_pages' : IDL.Nat,
    'total_items' : IDL.Nat,
    'has_next_page' : IDL.Bool,
    'current_page' : IDL.Nat,
    'items' : IDL.Vec(Category),
    'has_prev_page' : IDL.Bool,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'image' : IDL.Opt(IDL.Text),
    'price' : IDL.Nat,
  });
  const PaginationResult = IDL.Record({
    'total_pages' : IDL.Nat,
    'total_items' : IDL.Nat,
    'has_next_page' : IDL.Bool,
    'current_page' : IDL.Nat,
    'items' : IDL.Vec(Product),
    'has_prev_page' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'addCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'editProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'getAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCategories' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginationResult_1],
        ['query'],
      ),
    'getProducts' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginationResult],
        ['query'],
      ),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginationResult],
        ['query'],
      ),
    'getUser' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'initializeAuth' : IDL.Func([], [], []),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAdmin' : IDL.Func([IDL.Principal], [], []),
    'setUser' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };